name: nb-skdecide092-py38
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch::cpuonly
  - pytorch::pytorch
  - pip:
    - matplotlib
    - ipywidgets
    - ipympl
    - scikit-decide[all]==0.9.2
    - nbgitpuller
    - pyvirtualdisplay
    - PyOpenGL-accelerate
    - PyOpenGL
