name: nb-skdecide092-py38
dependencies:
  - python=3.8
  - pip
  - pip:
    - matplotlib
    - ipywidgets
    - ipympl
    - nbgitpuller
    - pyvirtualdisplay
    - PyOpenGL-accelerate
    - PyOpenGL
