ARG BASE_IMAGE=quay.io/pypa/manylinux2014_x86_64

FROM $BASE_IMAGE as build

RUN mkdir /scripts
COPY scripts/build-skdecide_dev.sh scripts/build-pip-install.sh /scripts/

RUN /scripts/build-skdecide_dev.sh
