name: Deploy doc

on:
  push:
    branches:
      - "doc_v1.1.0"
env:
  notebooks-branch: "notebooks-v1.1.0"
  release_tag: "v1.1.0"
  doc-version: "1.1.0"
  doc-clean: "false"
  doc-artifact-name: "doc"
  doc-path: "docs/.vuepress/dist"
  run-id-release: 28445995650

jobs:
  trigger-binder-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6  # checkout triggering branch to get scripts/trigger_binder.sh
      - name: Trigger a build for default binder env ref on each BinderHub deployments in the mybinder.org federation
        continue-on-error: true
        run: |
          binder_env_full_ref="${{ github.repository }}/${{ env.release_tag}}"
          echo Triggering binder environment build for ${binder_env_full_ref}
          bash scripts/trigger_binder.sh https://ovh.mybinder.org/build/gh/${binder_env_full_ref}
          bash scripts/trigger_binder.sh https://ovh2.mybinder.org/build/gh/${binder_env_full_ref}
          bash scripts/trigger_binder.sh https://notebooks.gesis.org/binder/build/gh/${binder_env_full_ref}

  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v21
        with:
          name: ${{ env.doc-artifact-name }}
          path: ${{ env.doc-path }}
          run_id: ${{ run-id-release }}
      - name: set doc-version-path
        id: set-doc-version-path
        run: |
          doc_version=${{ env.doc-version }}
          if [ -z "${doc_version}" ]; then
            doc_version_path="/"
          else
            doc_version_path="/version/${doc_version}/"
          fi
          echo "doc_version_path=${doc_version_path}" >> $GITHUB_OUTPUT

      - name: Deploy documentation in a version subfolder on GH pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ${{ env.doc-path }} # The folder the action should deploy.
          target-folder: ${{ steps.set-doc-version-path.outputs.doc_version_path }} # The folder the action should deploy to.
          commit-message: publish documentation
          single-commit: true
          clean: ${{ env.doc-clean }}
          clean-exclude: |
            "version/*"
